import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 1200, height: 900 } })
p.on('response', r => { if (r.url().includes('share')) console.log('RESP', r.status(), r.request().method(), r.url()) })
await p.goto('http://127.0.0.1:8910/', { waitUntil: 'networkidle' })
await p.waitForTimeout(2500)
console.log('rows:', await p.locator('a[href^="/m/"], .row').count())
await p.locator('a[href^="/m/"], .row').first().click()
await p.waitForTimeout(2000)
console.log('url after open:', p.url())
await p.locator('button[aria-label*="hare"]').first().click()
await p.waitForTimeout(1500)
console.log('has danger btn:', await p.locator('button.danger').count())
console.log('has create btn:', await p.locator('button.go').count())
await b.close()
