import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 1200, height: 900 } })
p.on('response', r => { if (r.url().includes('/api/shares')) console.log('RESP', r.status(), r.request().method()) })
await p.goto('http://127.0.0.1:8906/m/127/', { waitUntil: 'networkidle' })
await p.waitForTimeout(2500)
await p.locator('button[aria-label*="hare"]').first().click()
await p.waitForTimeout(1000)
const stop = p.locator('button.danger')
console.log('found stop button:', await stop.count())
await stop.click(); await p.waitForTimeout(250)
console.log('armed ->', (await stop.textContent())?.trim())
// Kill the share out from under the dialog: exactly what an expiry does.
await p.evaluate(() => fetch('/api/shares').then(r=>r.json()).then(l => l.length && fetch('/api/shares/'+l[0].token, {method:'DELETE'})))
await p.waitForTimeout(600)
await stop.click(); await p.waitForTimeout(1500)
console.log('dialog closed?', (await p.locator('div[role=dialog][aria-label="Share this session"]').count()) === 0)
console.log('share button back to unshared?', (await p.locator('button[aria-label="Share this session"]').count()) > 0)
await b.close()
